name: Trigger auto deployment for containerapp musicstore

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/musicstore-AutoDeployTrigger-30ecd0a6-004e-4754-aebe-8a5ca1a7f42b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caalbumapienacr.azurecr.io
          username: ${{ secrets.MUSICSTORE_REGISTRY_USERNAME }}
          password: ${{ secrets.MUSICSTORE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caalbumapienacr.azurecr.io/musicstore:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MUSICSTORE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n musicstore -g antchu_rg_0667 --server caalbumapienacr.azurecr.io --username  ${{ secrets.MUSICSTORE_REGISTRY_USERNAME }} --password ${{ secrets.MUSICSTORE_REGISTRY_PASSWORD }}
            az containerapp update -n musicstore -g antchu_rg_0667 --image caalbumapienacr.azurecr.io/musicstore:${{ github.sha }}
